version: "3"
services:
  db:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cricketscoresnap
      POSTGRES_USER: crick_admin
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: cricketscoresnap
      DB_USER: crick_admin
      DB_PASSWORD: your_password
    volumes:
      - .:/app

volumes:
  pgdata:
